Use getElementById instead of querySelector
The former allows any hash string to be used.

    > document.getElementById('123')
    null
    > document.querySelector('#123')
    SyntaxError: An invalid or illegal string was specified